name: Build against JDKs
on: [push, merge_group]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '23' ]
        architecture: [ 'x64' ]
    name: Build with JDK ${{ matrix.java }} on ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'oracle'
          architecture: ${{ matrix.architecture }}
      - name: Build with Maven
        run: mvn verify

